---
title: "Documentation of data analysis for C2M2 Kathmandu Portal"
author: "Arogya Koirala"
date: "3/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The purpose of this site is to document each and every step in the analysis of field data collected as part of the Tourism Workers and Tourism Business survey organized by Kathmandu Living Labs. 

To this effect, This repo contains all the R code for C2M2 Kathmandu portal, from KoboCollect to ADS preparation.


## Directory structure

- `/raw` contains data received as-is from Kobo
- `/utils` contains Rscripts shared by other modules
- `/experimental` contains test code, intermediate outputs and so on.
- `/core` contains Rscripts for the data pipeline, organized by survey, i.e., scripts encompassing the Kobo ➜ ADS for the workforce and business surveys.
- `/docs` houses this documentation


## Process

1. Base table schema design + generation of data dictionary.
1. Data cleaning, and base table preparation in R.
2. Export base table to PG database.
2. Use PG database as source for further analysis + ADS preparation codes.     
3. Create PG Dump file for populating APIDB.


## Notes
*Use this space to write down observations.*


#### March 30, 2021

**Rethinking the XLSForm**

Our survey forms are designed using the open source [ODK XForm](https://xlsform.org/en/) standard. We realized that there was a need to re-evaluate how variable names are assigned in the XLSForm. The motivation was to reduce any manual effort post survey that is spent on data pre-processing. In this context, we have the following suggestions for anyone designing a survey using XLSForm:

1. Design your own question coding scheme: The `name` column in the survey sheet, should have names that are a) easier to search and b) accurately represent what the column contains. If the column is a flag variable, clearly append a `_flg` suffix in the end. For our purposes we've come up with the following scheme:

  - Use i, p, n, m, o as prefixes for impact, preparedness, needs, outlook and user metadata respectively.
  - Use prefixes like `econ`, `empl`, `lvlhd` that allows future users of our data to easily 'understand the thematic focus of the column.

2. Use the same `list_name` as variable names: One think we'll have to do is to extract map choice responses to their labels. Having the same `list_name` is the choices sheet and the `name` column in the survey sheet can facilitae easy joins down the road.

**Rethinking the Worker Survey Questions**

A list of [suggestions](https://paper.dropbox.com/doc/Survey-feedback--BH5Ujlep32PI7nqQL20dDYpRAQ-tshKPalBNvj35iMU1i4V4) for the workers survey are available here.

----

#### March 25, 2021

**Should we `gitignore` raw files?**

Maybe its a good idea to do that, but might need to include the original XLSForm, in case someone wants to carry ourt their own deployment.     
 

