---
title: "Covid-19 and Employment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## unemployment ~ .


Factors to consider:

1. Edcation level
2. Experience
3. Whether they worked inside or outside the valley
4. What sector they belong to?
5. What gender they belong to?
6. Whether they recieved HHS training?
7. Whether they had Covid19 Vaccine?
8. What organization they are part of?





```{r}
library(nnet)
source("~/projects/c2m2/kathmandu-survey/utils/functions.R")
source("~/projects/c2m2/kathmandu-survey/utils/constants.R")
survey_data_path <- paste0(ROOT_URL, "raw/data/workers_data_20210425.xlsx")

workers_data <- IO.XlsSheetToDF(excel_sheets(survey_data_path)[1], survey_data_path)
workers <- workers_data %>% filter(!is.na(m_gender))

workers <- workers %>% mutate(efct_unemployed = ifelse(((i_empl_jb_prsnt_status == 3) | (i_empl_jb_prsnt_status == 4) ), T, F ))
ads <- workers %>% select(m_gender, m_age, m_edu_levl, m_years_of_experience, efct_unemployed, i_empl_jb_prsnt_status) 
ads

```

```{r}

ads <- ads %>% mutate(exp_3yrs_more = ifelse(m_years_of_experience == "3" | m_years_of_experience == "4" | m_years_of_experience == "5", T,F))

ads <- ads %>% mutate(edu_new_levl = ifelse(m_edu_levl == "1" , "1",ifelse( m_edu_levl == "2" | m_edu_levl == "3", "2", "3"  )))

ads$edu_new_levl <- factor(ads$edu_new_levl)
ads$m_edu_levl <- relevel(ads$m_edu_levl, "1")
mylogit <- glm(efct_unemployed ~ m_edu_levl, data = ads, family = "binomial")


summary(mylogit)
```


```{r }
ads$m_edu_levl <- relevel(ads$m_edu_levl, "2")
test <- multinom(efct_unemployed ~ ., data = ads)
test
```
```{r }
z <- summary(test)$coefficients/summary(test)$standard.errors
z
```
```{r }
p <- (1 - pnorm(abs(z), 0, 1))*2
p

```
```{r}
ads <- ads %>% mutate(exp_3yrs_more = ifelse(m_years_of_experience == "3" | m_years_of_experience == "4" | m_years_of_experience == "5", T,F))

test <- multinom(efct_unemployed ~ m_years_of_experience + m_edu_levl, data = ads)
test
```
